name: Cypress_CI

on: [workflow_dispatch] # workflow_dispatch allows you to run this workflow manually from the Actions tab
#on: [push,workflow_dispatch] # workflow_dispatch allows you to run this workflow manually from the Actions tab

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: adresar
        run: |
          mkdir -p path/to/artifact
          echo hello > path/to/artifact/world.txt
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          #build: npm run start #build
          start: npm run test --record false
