name: Cypresse CI

on: [workflow_dispatch] # workflow_dispatch allows you to run this workflow manually from the Actions tab
#on: [push,workflow_dispatch] # workflow_dispatch allows you to run this workflow manually from the Actions tab

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout #This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
        uses: actions/checkout@v2
            
      - name: Cypress run #Setup a run of Cypress on Github
        uses: cypress-io/github-action@v2
        with:
          start: npm run test --record false #video from test is not recorded
               
      - name: Upload report #Upload mochawsome report do Actions Artifacts
        uses: actions/upload-artifact@master
        with:
          name: E2E Test Reports
          path: TestReport/*
          
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
