name: upload

on: [workflow_dispatch] # workflow_dispatch allows you to run this workflow manually from the Actions tab
#on: [push,workflow_dispatch] # workflow_dispatch allows you to run this workflow manually from the Actions tab

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout #This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
        uses: actions/checkout@v2
        
      - name: adresar
        run: |
          mkdir -p path/to/artifact
          echo hello > path/to/artifact/world.txt
              
      - name: Upload report
        uses: actions/upload-artifact@master
        with:
          name: E2E Test Reports
          path: path/to/artifact/
